resilience4j:
  circuitbreaker:
    configs:
      defaultconfig:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
    instances:
      general-app-circuitbreaker: 
        base-config: defaultconfig
  timelimiter:
    configs:
      defaultconfig:
        timeout-duration: 6s
    instances:
      general-app-circuitbreaker:
        base-config: defaultconfig
        
spring:
  cloud:
    gateway:
      routes:
      - id: petcare-core
        uri: lb://petcare-core
        predicates:
          - Path=/api/appointments/**
          - Path=/api/clients/**
          - Path=/api/pets/**
          - Path=/api/reports/**
          - Path=/api/vet-entities/**
          - Path=/api/vets/**
        filters:
          - StripPrefix=1
          - name: CircuitBreaker
            args:
              name: general-app-circuitbreaker
              statusCodes: 500
      - id: petcare-security
        uri: lb://petcare-security
        predicates:
          - Path=/api/users/**
        filters:
          - StripPrefix=1
          - name: CircuitBreaker
            args:
              name: general-app-circuitbreaker
              statusCodes: 500
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
      client:
        registration:
          client-gateway:
            provider: spring
            client-id: client-gateway
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:8090/authorized"
            scope:
              - openid
              - profile
              - client
              - vet
              - vet_entity
              - root
            client-name: client-gateway
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"