resilience4j:
  circuitbreaker:
    configs:
      defaultconfig:
        sliding-window-size: 6
        failure-rate-threshold: 50
        wait-duration-in-open-state: 20s
        permitted-number-of-calls-in-half-open-state: 4
    instances:
      general-app-circuitbreaker: 
        base-config: defaultconfig
  timelimiter:
    configs:
      defaultconfig:
        timeout-duration: 6s
    instances:
      general-app-circuitbreaker:
        base-config: defaultconfig
        
spring:
  cloud:
    gateway:
      routes:
      - id: petcare-core
        uri: lb://petcare-core
        predicates:
          - Path=/api/appointments/**
          - Path=/api/clients/**
          - Path=/api/pets/**
          - Path=/api/reports/**
          - Path=/api/vet-entities/**
          - Path=/api/vets/**
        filters:
          - StripPrefix=1
          - name: CircuitBreaker
            args:
              name: general-app-circuitbreaker
              statusCodes: 500
      - id: petcare-security
        uri: lb://petcare-security
        predicates:
          - Path=/api/users/**
        filters:
          - StripPrefix=1
          - name: CircuitBreaker
            args:
              name: general-app-circuitbreaker
              statusCodes: 500